services:
  - type: web
    name: excel-handler-django
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn blast_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: DJANGO_SETTINGS_MODULE
        value: blast_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: excel-handler-tiyc.onrender.com

